### ISSUE TITLE
Integration in Alire package manager

### ISSUE THREAD

**Issue by Fabien-Chouteau** [medsec/ada-fuse#1]
Hi,

This is a nice project you should consider making it available in Alire: https://alire.ada.dev/docs/#publishing-your-projects-in-alire

**Comment by Fabien-Chouteau** [comment]
I made an Alire manifest for `ada-fuse` based on my #2 pull-request:

`ada_fuse.toml`:
```toml
[general]
description = "Ada bindings for Fuse (Filesystem in Userspace)"
website = "https://github.com/medsec/ada-fuse"
authors  = ["Alexander Herr <thissideup@riseup.net>",
               "Nicolai Ruckel <nicolai.ruckel@uni-weimar.de>",
               "christopher-l <christopher.luebbemeier@googlemail.com>"]
maintainers = ["Alexander Herr <thissideup@riseup.net>",
               "Nicolai Ruckel <nicolai.ruckel@uni-weimar.de>",
               "christopher-l <christopher.luebbemeier@googlemail.com>"]
maintainers-logins = ["alex-dot", "NicolaiRuckel", "christopher-l", "medsec"]
licenses = ["MIT"]
project-files = ["ada_fuse_build.gpr"]

[general.gpr-externals]
ADA_FUSE_SYSTEM = ["Linux x86_64", "Linux i386", "Darwin i386", "Darwin x86_64"]

[general.gpr-set-externals.'case(os)']
linux = { ADA_FUSE_SYSTEM = "Linux x86_64" }
macos = { ADA_FUSE_SYSTEM = "Darwin x86_64" }

[general.available.'case(os)']
linux   = true
macos   = true
windows = false
'...'   = false

["1.0.0"]
origin = "https://github.com/medsec/ada-fuse/releases/download/"
origin-hashes = ["sha512:"]
["1.0.0".depends-on]
libfuse = "^2.0.0"
```
If you want to publish it, you just have to upload an archive on GitHub release and set the `origin` and `origin-hashes` fields above.

I also made an Alire external crate to automatically install `libfuse-dev` on Ubuntu/Debian:
`libfuse.toml`:
```toml
[general]
description = "Interface for userspace programs to export a filesystem"
licenses = ["LGPL 2.1"]
maintainers = ["fabien.chouteau@gmail.com"]
maintainers-logins = ["Fabien-Chouteau"]

[[external]]
kind = "system"
    [external.origin.'case(distribution)']
    'debian|ubuntu' = ["libfuse-dev"]
```
